### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Nzii3** [Smoose-bv/whmcspy#3]
Code:
Just a simple `whmcs.create_client()` call with every parameter needed.

Error:
<details>
<summary>…</summary>
<codeblock>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/jishaku/features/python.py", line 145, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/home/container/.local/lib/python3.9/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/home/container/.local/lib/python3.9/site-packages/jishaku/repl/compilation.py", line 140, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/home/container/.local/lib/python3.9/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 1, in _repl_coroutine
    whmcs.add_client(firstname='Test', lastname='Client', email='x@gmail.com', address1='optional', city='x', state='x', postcode='123456', country='US', phonenumber='1+xxxxxxxx', password2='thebestpassword321')
  File "/home/container/.local/lib/python3.9/site-packages/whmcspy/api.py", line 184, in add_client
    result = self.call(
  File "/home/container/.local/lib/python3.9/site-packages/whmcspy/api.py", line 104, in call
    response_ = response.json()
</codeblock>
*`x` is a placeholder for information I actually used*

</details>

**Comment by Nzii3** [comment]
I have this as my url for requests exactly, but x would be my domain. Is this correct?
`https://x.com/whmcs/includes/api.php`
Is this the correct url to post to? And yes the API credentials from WHMCS are correct and it has all the permissions.

**Comment by Nzii3** [comment]
@siebz0r
